config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'  
  get "my_portfolio", to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'user_stocks', to: 'user_stocks#create'
  get '/user_stock_delete/:id', to: 'user_stocks#destroy', as: 'user_stocks_delete'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search', as: 'search_friend'
  get '/unfriend/:id', to: 'friendships#unfriend', as: 'unfriend'
  get '/add_friend/:id', to: 'friendships#add_friend', as: 'add_friend'

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            secret_token: Rails.application.credentials.iex_client[:sandbox_secret_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
        )
        #begin and rescue is like try catch
        begin
            #now return the price
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,  last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end     
    end


    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def stock_already_tracked?(ticker_symbol)
    #first check if the stock is already in the database even 
    stock = Stock.check_db(ticker_symbol)
    #if it's not in the database it's for sure not tracked by the user, so return false if stock is nil
    return false unless stock
    #then check if the stock is in the user's stocks, aka implied as self.stocks but shorthand written as stocks.where etc
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    #the self. is already implied in front of "stocks"
    #returns true if the self.stocks count is under the limit of 10
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    #check under the limit, and check if the stock is NOT already tracked
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    #return the first name and last name in a string if self has first_name or last_name
    return "#{first_name} #{last_name}" if first_name || last_name
    #else, just return this string that says anonymous
    "Anonymous" 
  end

  #class level method requires self
  def self.matches(field_name, param)
    #Active record query that returns array of users who's field name contains wildcarded param
    where("#{field_name} like ?", "%#{param}%")
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  #search method to prepare the param for query
  def self.search(param)
    #remove spaces before and after
    param.strip!
    #by concatenating the returns here you ensure you check if the search params match  any of the three fields
    #even if that means 2/3 fields will return blanks, one of the concatenated returns will contain something
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq   #uniq method ensures you won't return the same user twice
    #if there are no matches at all, return nil
    return nil unless to_send_back
    to_send_back
  end
  
  def except_current_user(users)
    #use the reject method to loop through the users array, and and if any of their ids match the current user, then take them out 
    users.reject! { |user| user.id == self.id }
    
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def add_friend
        friend = User.find(params[:id])
        #then create a friendship relationship with the friend you found
        current_user.friendships.build(friend_id: friend.id)
        if current_user.save
            flash[:notice] = "You are now following #{friend.full_name}"
        else
            flash[:alert] = "There was something wrong with the tracking request"
        end
        redirect_to my_friends_path
    end

    def unfriend
        #find and destroy the relationship
        #where returns an array, so make sure that you select the first (and only relationship) returned in that array
        friendship = current_user.friendships.where(friend_id: params[:id]).first
        friendship.destroy
        flash[:notice] = "Stopped Following"
        redirect_to my_friends_path
    end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        @user = current_user
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                @tracked_stocks = current_user.stocks
                render 'users/my_portfolio'
            else 
                flash[:alert] = "Please enter a valid symbol to search"
                redirect_to my_portfolio_path
            end
        else
            flash[:notice] = "Please enter a symbol to search"
            redirect_to my_portfolio_path
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "#{stock.name} was successfully added to your portfolio!"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first #because the where method returns an array, we have to return the first one
        @user_stock.destroy
        flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends_result = User.search(params[:friend])
      #call the except_current_user method you made in the User.rb class to take out the current user from that array
      @friends = current_user.except_current_user(@friends_result)
      if @friends_result
          @friends = current_user.friends
          render 'users/my_friends'
      else 
          flash[:alert] = "We couldn't find that friend! Please try again"
          redirect_to my_friends_path
      end
    else
      flash[:notice] = "Please enter a friend's name"
      redirect_to my_friends_path
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<h3>People you are friends with</h3>

<div class = "row">
    <div class = "col-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Email</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |friend| %>
                <tr>
                    <th scope="row"><%= friend.email%></th>
                    <td><%= friend.full_name%></td>
                    <td>
                        <%= link_to "Stop Following", unfriend_url(friend), class: "btn btn-sm btn-warning"%>
                        <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>

app/views/friends/_result.html.erb
<% if @friends_result %>
    <div class = "card card-header results-block">
        <table class = "col-md-12">
            <tbody>
                <% @friends_result.each do |friend| %>
                    <tr>
                        <td><strong>Name: </strong><%= friend.full_name %></td>
                        <td><strong>Email: </strong><%= friend.email %></td>
                        <td>
                            <strong>Actions: </strong><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
                            <% if !current_user.friends.include?(friend) %>
                                <%= link_to "Add Friend", add_friend_url(friend), class: "btn btn-sm btn-success" %>
                            <% else %>
                                <span class = "badge badge-secondary">
                                    You are friends
                                </span>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <%# if the name of the message object passed in is notice, do success (green), if not, do danger %>
     <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <div style = "display: flex; justify-content: space-between">
            <h2 class="alert-heading">
                <%= msg%>
            </h2>
            <button type="button" class="close bg-transparent border-0" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" ><strong>x</strong></span>
            </button>
        </div>
    </div>
<% end %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class = "container">
        <%= link_to "FinanceTracker", root_path, class:"navbar-brand"%>
        <% if current_user %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <%= link_to "Portfolio", my_portfolio_path, class: "dropdown-item"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Friends", my_friends_path, class: "dropdown-item"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to edit_user_registration_path, class: 'dropdown-item' do%>
                            <%= fa_icon 'edit' %> Edit Profile
                        <%end %>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <ul class = "navbar-nav ml-auto">
                    <li class = "nav-item user-name">
                        <%= fa_icon 'user'%> <%= current_user.full_name%>
                    </li>
                    <li class = "nav-item">
                        <%= link_to("Logout", destroy_user_session_path, class: "btn btn-xs btn-danger logout-button", method: :delete)%>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Financetracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation"%>
    <div class = "container">
      <% render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if !@tracked_stocks.empty?%>
    <div class = "row">
        <div class = "col-9">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracked_stocks.each do |stock| %>
                    <tr>
                        <th scope="row"><%= stock.ticker%></th>
                        <td><%= stock.name%></td>
                        <td><%= stock.last_price%></td>
                        <td>
                            <% if current_user.can_track_stock?(stock.ticker)%>
                                <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-sm btn-success" %>
                            <% elsif current_user.id != @user.id%>
                                <span class = "badge badge-secondary">
                                    You are already tracking 
                                    <% if !current_user.under_stock_limit?%>
                                        10 stocks
                                    <% end%>
                                    <% if current_user.stock_already_tracked?(stock.ticker)%>
                                        this stock
                                    <% end %>                    
                                </span>
                            <% end %>
                            <% if current_user.id == @user.id %>
                                <%= link_to "Remove", user_stocks_delete_url(stock), class: "btn btn-sm btn-warning"%>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
<% end %>

app/views/stocks/create.html.erb
asd;fil

app/views/users/_result.html.erb
<% if @stock %>
    <div class = "card card-header results-block">
        <strong>Symbol: </strong><%= @stock.ticker %>
        <strong>Name: </strong><%= @stock.name %>
        <strong>Price: </strong><%= @stock.last_price %>
        <% if current_user.can_track_stock?(@stock.ticker)%>
            <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-xs btn-success" %>
        <% else %>
            <span class = "badge badge-secondary">
                You are already tracking 
                <% if !current_user.under_stock_limit?%>
                    10 stocks
                <% end%>
                <% if current_user.stock_already_tracked?(@stock.ticker)%>
                    this stock
                <% end %>                    
            </span>
        <% end %>
    </div>

<% end %>

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<%= render 'layouts/messages' %>


<div class = "search-area">
    <h3>Search Friends</h3>
    <%= form_tag search_friend_path, method: :get do %>
        <div class = "form-group row">
            <div class = "col-sm-9 no-right-padding">
                <%= text_field_tag :friend, params[:friend], placeholder: "Friend's Name", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class = "col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do%>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <%end%>
</div>

<%= render 'friends/result' %>

<% if !@friends.empty?%>
    <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portoflio</h1>

<%= render 'layouts/messages' %>

<div class = "search-area">
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, method: :get do %>
        <div class = "form-group row">
            <div class = "col-sm-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class = "col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do%>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <%end%>
</div>
<%= render 'users/result'%>

<% if !@tracked_stocks.empty?%>
    <%= render 'stocks/list'%>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class = "card card-header results-block">
    <table class = "col-md-12">
        <tbody>
            <tr>
                <td><strong>Name: </strong><%= @user.full_name %></td>
                <td><strong>Email: </strong><%= @user.email %></td>
                <td>
                    <% if !current_user.friends.include?(@user) %>
                        <%= link_to "Add Friend", add_friend_url(@user), class: "btn btn-xs btn-success" %>
                    <% else %>
                        <span class = "badge badge-secondary">
                            You are friends
                        </span>
                    <% end %>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<% if !@tracked_stocks.empty?%>
    <%= render 'stocks/list'%>
<% else %>
    <p class= 'lead'>
        This user is not tracking any Stocks
    </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker App</h1>

<%= render 'layouts/messages' %>